### ISSUE TITLE
Research Google Test

### ISSUE THREAD

**Issue by t-pereira06** [SEAME-pt/HotWheels-Cluster#14]
`Description:` What is it? How does it work and how can we implement it?

</br>

`Definition of done:`  This issue is considered done when the above questions are clearly answered

**Comment by t-pereira06** [comment]
## What is Google Test?
Google Test, often referred to as gtest, is a specialized library utilized to conduct unit testing in the C++ programming language.
It can be compiled for a diverse range of computer systems, such as POSIX and Microsoft Windows.
This adaptability facilitates the execution of unit tests on both C and C++ codebases, with minimal alterations required in the source code.

## How to install Google Test
To install Google Test, we need to do this:

Install required packages
```bash
sudo apt-get update
sudo apt-get install libgtest-dev cmake
```
Build Google Test from source (since Ubuntu only installs source files)
```bash
cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
```
Copy the library files
```bash
sudo cp lib/*.a /usr/lib
```

## How does it work and how can we implement it?
To test how it works, create a directory tree like this:

```bash
test
├── build (directory)
├── CMakeLists.txt
├── math_test.hpp
└── math_test.cpp
```

Then make this changes on files:

math_test.cpp
```bash

#include <gtest/gtest.h>
#include "math.h"

TEST(MathTest, Addition) {
    EXPECT_EQ(Math::add(2, 3), 5);
    EXPECT_EQ(Math::add(-2, 3), 1);
    EXPECT_EQ(Math::add(0, 0), 0);
}

TEST(MathTest, Multiplication) {
    EXPECT_EQ(Math::multiply(2, 3), 6);
    EXPECT_EQ(Math::multiply(-2, 3), -6);
    EXPECT_EQ(Math::multiply(0, 5), 0);
}

int main(int argc, char **argv) {
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```

math_test.hpp
```bash
class Math {
public:
    static int add(int a, int b) { return a + b; }
    static int multiply(int a, int b) { return a * b; }
};
```

CMakeLists.txt
```bash
# CMakeLists.txt
cmake_minimum_required(VERSION 3.10)
project(gtest_example)

# Enable testing
enable_testing()

# Find GTest package
find_package(GTest REQUIRED)

# Add the executable
add_executable(math_test math_test.cpp)

# Link against GTest
target_link_libraries(math_test GTest::GTest GTest::Main)

# Add test
add_test(NAME math_test COMMAND math_test)
```

Then, to bulld and run the tests:
```bash
mkdir build
cd build
cmake .. make ./math_test
```

After that, output will be like this:
```bash
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from MathTest
[ RUN      ] MathTest.Addition
[       OK ] MathTest.Addition (0 ms)
[ RUN      ] MathTest.Multiplication
[       OK ] MathTest.Multiplication (0 ms)
[----------] 2 tests from MathTest (0 ms total)
```

**Comment by reomelo** [comment]
Good research Tiago. I think we'll most definitely implement Gtests in a near future so this information we'll be very useful.
