### ISSUE TITLE
Implement controls

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#20]
`Description:` Implement movement keys to allow user control. Each key input generates a signal to control the wheels motors.

</br>

`Definition of done:` This issue is considered done when the program accepts input and sends signals to the car that interact with the wheels motors, changing values in real time.

**Comment by t-pereira06** [comment]
Controls are working right now, but there's a problem where the car sometimes reboots itself and also it stops recognizing the controller.
This was tested with the old version of the OS, we are going to test on this new one.

**Comment by t-pereira06** [comment]
In the new version, the OS does not reboot itself but it still stops recognizing the controller.

**Comment by reomelo** [comment]
The direction controls still shutdown the car. This issue will be moved to next sprint

**Comment by reomelo** [comment]
Finished in #51
