### ISSUE TITLE
Research about ROS (Robot Operating System)

### ISSUE THREAD

**Issue by t-pereira06** [SEAME-pt/HotWheels-Cluster#23]
`Description:` What is it? Will it be useful to use? How to implement it?

</br>

`Definition of done:` This issue is considered done when the above questions are clearly answered

**Comment by reomelo** [comment]
### What is it?
The ROS2 is a middleware that uses a Data Distribution Service (DDS) to communicate.

[CORE CONCEPTS]
**Nodes:** Individual processes that perform computation in a distributed robotic system.
**Topics:** Channels for publish/subscribe messaging between nodes.
**Services:** Enable synchronous communication (request/response model).
**Actions:** Allow asynchronous task execution with feedback.
**Parameters:** Configuration variables that can be dynamically adjusted.

![Image](https://github.com/user-attachments/assets/2e483d51-e997-4e54-bb7a-d4b4013bf74d)


### Use cases
This middleware is commonly used in autonomous programming and contains tools like Nav2 (ROS2 Navigation Stack) and machine learning that are very useful when it comes to autonomous navigation and obstacle avoidance. However it would be necessary to translate CAN messages into ROS2 topics and vice versa using a package like _**ros2_canopen**_.

In terms of implementation, an example would be something like the Arduino handling raw CAN communication for low-level motor and sensor control, and the Jetson Nano running ROS2 for high-level monitoring.

### Do we need it?
It would be an interesting method to use but from my understanding is very similar to a CAN Network and much more difficult to implement. I think we should just stick to the CAN communication protocol combined with multithreading and if in the future we come to the conclusion that we actually need it we just come back to this issue and adapt the code.
