### ISSUE TITLE
Research about clang-tidy Checks

### ISSUE THREAD

**Issue by Fle-bihh** [SEAME-pt/HotWheels-Cluster#30]
`Description:` Research the different checks available with clang-tidy library. Which ones are useful and should be used, which ones are overkill.

</br>

`Definition of done:` This issue is done once the final clang-tidy configuration (and associated checks) is chosen.

**Comment by Fle-bihh** [comment]
Up : These are the core checks we will use. Still open for refining once all team members have experienced them.

**Comment by reomelo** [comment]
The checks seem the most accurate to our project so an issue will soon be created regarding their implementation
