### ISSUE TITLE
Setup ssh connection with Nvidia computer.

### ISSUE THREAD

**Issue by Fle-bihh** [SEAME-pt/HotWheels-Cluster#31]
`Description:` Open ssh ports on Nvidia computer to allow the team members to access it without the need of keyboard / mouse.

</br>

`Definition of done:` The issue is done once every member has successfully established an ssh connection between its computer and the car computer.

**Comment by Fle-bihh** [comment]
ssh server is setup on Nvidia computer, but ssh connections seems to be down at school for the moment.

**Comment by MicchelFAB** [comment]
The serve is configured, for now it responds on ip 10.19.246.15, in case this IP did not work it is possible connect to the Jetnano using the USB cable on the board and PC with the ip 192.168.55.1 `default`
