### ISSUE TITLE
Cluster Widget creation

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#33]
`Description:` Creation of a Widget that resembles the mockup design in #5.

</br>

`Definition of done:` This issue is considered as done when we have a graphical interface of the cluster

**Comment by Fle-bihh** [comment]
https://github.com/user-attachments/assets/1b11620f-d497-452b-9744-dfbb673f745e
Main window with right sizes. Root cpp files controls speed and maxSpeed of the SpeedIndicatorModule.

**Comment by reomelo** [comment]
The widget is very cool as works perfectly. Good job
