### ISSUE TITLE
Research CAN bus protocol

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#4]
`Description:` Study about how the CAN bus protocol works, which components are compatible with it and how does the communication between them is executed.

Useful links: https://dewesoft.com/blog/what-is-can-bus
<br>

`Definition of done:` This issue is considered done when the team is fully capable of explaining how the protocol works

**Comment by Fle-bihh** [comment]
CAN Bus Protocol Documentation

    Connect all devices together:
    Each device can send data on the network through the bus.

    Data Usage:
    Each device receives all messages on the bus but uses or ignores them based on the ID field.

    Signal Integrity:
        CAN uses two lines (CANH and CANL) to transmit data differentially.
        It measures the voltage difference between the two lines, making the system immune to common-mode noise (e.g., electromagnetic interference).

    CAN Data Frame:

Start Bit | ID Bits | Control Bits | Data | CRC Field | End of Frame

    Start Bit: Marks the beginning of the frame.
    ID Bits: Used to prioritize messages and ensure bus arbitration.
    Control Bits: Specify additional information (e.g., data length).
    Data Field: The actual payload being transmitted.
    CRC Field: Ensures data integrity by verifying the transmitted data against the recalculated CRC.
    End of Frame: Marks the completion of the transmission and ensures synchronization.
