### ISSUE TITLE
Github actions compilation

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#43]
`Description:` Configure GitHub actions to compile the Qt project and deliver the executable. Is it possible to call this action when someone git pulls from the main branch?

</br>

`Definition of done:` This issue is considered as done when the action has been implemented and is working properly

**Comment by t-pereira06** [comment]
For example, when the main branch is updated display something on the cluster, asking to update the system, and then execute a systemctl restart service to get the new updates from the main and then running it with the new version

**Comment by t-pereira06** [comment]
Github action to make the executable for car controls is working
