### ISSUE TITLE
Create car services

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#44]
`Description:` Create services for the car controls ant the cluster itself

</br>

`Definition of done:` This issue is considered as done when the respective services have been created and are working properly

**Comment by t-pereira06** [comment]
So far, the service to control the movement of the car is working, just waiting to see how we can fix the issue of the board shutting down to proper test the service.

Waiting for the cluster GUI to be ready to then deploy the cluster service and test to make sure it runs when the car boots
