### ISSUE TITLE
Add speedometer animation

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#46]
`Description:` Add an animation to the speedometer to remove the visual delay effect

</br>

`Definition of done:` This issue is considered as done when an animation has been implemented that moves the speedometer pointer fluently

**Comment by Fle-bihh** [comment]
Smooth animation, Needs to be tested with can speeds to adjust animation values.

https://github.com/user-attachments/assets/53e704c9-87d5-482d-b780-3edfa57bcb9f

**Comment by reomelo** [comment]
After testing and adjusting the animation it's now running smoothly
