### ISSUE TITLE
Instrument Cluster Design

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#5]
`Description:` Simple design of how the instrument cluster should look like at the end of the project
<br>
`Definition of done:` This issue is considered done when there's a mockup of the instrument cluster display

**Comment by t-pereira06** [comment]
## This is just a simple instrument clster, to guide us until the final one is done

![cluster](https://github.com/user-attachments/assets/4faebdfc-3eca-4695-81c7-03400ca8dceb)
