### ISSUE TITLE
Fix car movement issue

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#51]
`Description:` Fix the shutting down on steering issue. Is it the servo? The nano board? The scripts? Find out

</br>

`Definition of done:` This issue is considered as done when the team can maneuver the car freely without any problems or errors

**Comment by t-pereira06** [comment]
Right now, the car still shuts down even with the new servo. We think there is a board issue, as we tested our SD card on another car and it worked fine. Maybe a replacement is needed.

**Comment by reomelo** [comment]
We finally fixed the problem. It was indeed a hardware issue in the expansion board. After replacing it with a new one it worked perfectly. The raspberry won't be used after all. We can move on now!
