### ISSUE TITLE
Research Multithreading

### ISSUE THREAD

**Issue by reomelo** [SEAME-pt/HotWheels-Cluster#8]
`Description:` Study about multihreads, mutexes and traffic lights. What's the best way to implement them in our project?
</br>

` Definition of done: ` This issue is considered as done when a clear base structure for the project is designed

**Comment by MicchelFAB** [comment]
That's an excellent way to deepen your understanding of multithreading and container usage in C++. If you need help with implementation details, debugging, or exploring advanced multithreading concepts, let me know!
